### ISSUE TITLE
Menu sumindo

### ISSUE THREAD

**Issue by sio-iago** [IsTheJack/ro-dash#1]
Browser: Safari (mas provavelmente deve ocorrer nos outros)
Problema: O redimensionamento muda o menu para sanduíche. Porém, ao redimensionar de volta o menu simplesmente some.

**Comment by IsTheJack** [comment]
**Muito obrigado** por notar, amigo... Amh mesmo irei consertar esse problema... Qualquer sugestão de componente ou novas issues, pode ficar a vontade...

**Comment by sio-iago** [comment]
Agradeço por contribuir. A propósito, o painel ficou show!
